FROM postgres:latest

# ----------//atualiza o sistema//--------------

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y vim

# ----------//cria o usuario e o database do postgres//--------------

ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD admin
ENV POSTGRES_DB api_crud_db

# ----------//inicializa o banco de dados//--------------

USER postgres

EXPOSE 5432

RUN initdb && echo "host all all 0.0.0.0/0 trust" >> /var/lib/postgresql/data/pg_hba.conf
